Quick edit (#64)
* Working function delete bulk/quick

also added alter table for checking if the allergy is default, wouldn't want to delete a default allergy/diet.

* Complete delete function

* Check to prevent deleting default

* added and deleted user feedback

* update

* update

* changes

* requested changes

* UML

* UML

* Quick edit changes

* changes

* changes

* changes

* werkende quick actions

* conform

* changes

* changes

* changes

* changes

* changes

* changes

* changes

* changes

* changes

* improved feedback on adding allergens

* changes

* fixes

* removed test code and changes

* fixes

* UML

* fixed attachment bug

* requested changes + UML

* foutje.. heb ik weggehaald

* fixes

* changes

* fixes

* allergen type fix

* delete fix

* fixes

* fixes

* testcode removal + uml

* required file

* changes

* changes

* changes

* comments and uml

* comment

* changes

* changes

* changes

* changes

* fixes

* changes

* requested changes

* changes

* removed upload_dir

* better code

* fixes

* fixes

* changes

* changes

* changes

* Showing icon, custom button

* update

* changes

* changes

* changes

* update file select

* changes

* Mime types

ERROR: image vervangen met een nieuwe in de quick edit werkt nog niet!

* bugfix

* update

* changes

* changes

* removed an if-statement

* requested changes

* safety update

* Update commit

* Working update function

Improved page handling, readability, query's.

--Still needs the conform--

---------

Co-authored-by: Maik Hendriks <Maik.Hendriks@ictoria.nl>